version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventaris_app
    restart: unless-stopped
    ports:
      - "8100:80"
    volumes:
      - .:/var/www/html
    environment:
      # Jika database ada di host (komputer lokal Anda), docker di Mac/Windows
      # membutuhkan host.docker.internal untuk mengakses localhost milik host.
      - DB_HOST=host.docker.internal
    networks:
      - inventaris-network

networks:
  inventaris-network:
    driver: bridge
